-- Artists
INSERT INTO ARTIST (name) VALUES ('John Doe');
INSERT INTO ARTIST (name) VALUES ('Jane Smith');
INSERT INTO ARTIST (name) VALUES ('David Johnson');
INSERT INTO ARTIST (name) VALUES ('Emily Davis');
INSERT INTO ARTIST (name) VALUES ('Michael Wilson');
INSERT INTO ARTIST (name) VALUES ('Sarah Brown');
INSERT INTO ARTIST (name) VALUES ('Robert Miller');
INSERT INTO ARTIST (name) VALUES ('Olivia Taylor');
INSERT INTO ARTIST (name) VALUES ('Daniel Martinez');
INSERT INTO ARTIST (name) VALUES ('Ava Anderson');

-- Song: Imagine
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Imagine', 1, '3:03');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (1, 'Pop');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (1, 'Folk');

-- Song: Hotel California
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Hotel California', 2, '6:30');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (2, 'Rock');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (2, 'Classic Rock');

-- Song: Billie Jean
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Billie Jean', 3, '4:54');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (3, 'Pop');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (3, 'R&B');

-- Song: Smells Like Teen Spirit
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Smells Like Teen Spirit', 4, '5:01');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (4, 'Grunge');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (4, 'Alternative Rock');

-- Song: Like a Rolling Stone
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Like a Rolling Stone', 5, '6:13');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (5, 'Rock');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (5, 'Folk Rock');

-- Song: Purple Haze
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Purple Haze', 6, '2:51');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (6, 'Rock');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (6, 'Psychedelic Rock');

-- Song: Yesterday
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Yesterday', 7, '2:05');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (7, 'Pop');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (7, 'Baroque Pop');

-- Song: HALLOOOOO
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'HALLOOOOO', 8, '2:05');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (8, 'Pop');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (8, 'Experimental');

-- Song: Stairway to Heaven
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Stairway to Heaven', 9, '8:02');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (9, 'Rock');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (9, 'Hard Rock');

-- Song: Thriller
INSERT INTO SONG (VERSION, TITLE, ARTIST_ID, LENGTH) VALUES (0, 'Thriller', 10, '5:57');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (10, 'Pop');
INSERT INTO SONG_GENRES (SONG_ID, GENRES) VALUES (10, 'Funk');
